/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author digim
 */
public class Menu_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu_Admin() {
        setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        
        Login login = new Login();
        txtUsuario.setText(login.TipoUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTMascotasEnAdop = new javax.swing.JButton();
        BTMascotas_Encontradas = new javax.swing.JButton();
        BTtendencia_responsable = new javax.swing.JButton();
        BTmascotas_perdidas = new javax.swing.JButton();
        txtUsuario = new javax.swing.JLabel();
        BTcerrars = new javax.swing.JButton();
        BTFormularios = new javax.swing.JButton();
        BTFundaciones = new javax.swing.JButton();
        BTusuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido:");

        BTMascotasEnAdop.setText("Ir a Mascotas en Adopcion");
        BTMascotasEnAdop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMascotasEnAdopActionPerformed(evt);
            }
        });

        BTMascotas_Encontradas.setText("Ir a Mascotas Encontradas");
        BTMascotas_Encontradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMascotas_EncontradasActionPerformed(evt);
            }
        });

        BTtendencia_responsable.setText("Ir a Tenencia Responsable");
        BTtendencia_responsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTtendencia_responsableActionPerformed(evt);
            }
        });

        BTmascotas_perdidas.setText("Ir a Mascotas Perdidas");
        BTmascotas_perdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTmascotas_perdidasActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtUsuario.setText("@NOMBRE ADMIN");

        BTcerrars.setText("Cerrar Sesion");
        BTcerrars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcerrarsActionPerformed(evt);
            }
        });

        BTFormularios.setText("Ir a Formularios");
        BTFormularios.setMaximumSize(new java.awt.Dimension(93, 23));
        BTFormularios.setMinimumSize(new java.awt.Dimension(93, 23));
        BTFormularios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFormulariosActionPerformed(evt);
            }
        });

        BTFundaciones.setText("Ir a Fundaciones");
        BTFundaciones.setMaximumSize(new java.awt.Dimension(93, 23));
        BTFundaciones.setMinimumSize(new java.awt.Dimension(93, 23));
        BTFundaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFundacionesActionPerformed(evt);
            }
        });

        BTusuarios.setText("Ir a Usuarios");
        BTusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTusuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTcerrars)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(txtUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BTMascotasEnAdop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTmascotas_perdidas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BTMascotas_Encontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTtendencia_responsable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTFormularios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(BTusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(BTFundaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario)
                            .addComponent(jLabel1)))
                    .addComponent(BTcerrars))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTtendencia_responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTmascotas_perdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTMascotasEnAdop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTFundaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTFormularios, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTMascotas_Encontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTMascotas_EncontradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMascotas_EncontradasActionPerformed
        Mascotas_Encontradas ME = new Mascotas_Encontradas();
        ME.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTMascotas_EncontradasActionPerformed

    private void BTtendencia_responsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTtendencia_responsableActionPerformed
        Tenencia_Responsable TR = new Tenencia_Responsable();
        TR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTtendencia_responsableActionPerformed

    private void BTmascotas_perdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTmascotas_perdidasActionPerformed

        Mascotas_Perdidas MP = new Mascotas_Perdidas();
        MP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTmascotas_perdidasActionPerformed

    private void BTcerrarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcerrarsActionPerformed
        Login lo= new Login();
        lo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTcerrarsActionPerformed

    private void BTFormulariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFormulariosActionPerformed
        Formularios FM = new Formularios();
        FM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTFormulariosActionPerformed

    private void BTMascotasEnAdopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMascotasEnAdopActionPerformed
        Mascotas_en_Adopcion Mas = new Mascotas_en_Adopcion();
        Mas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTMascotasEnAdopActionPerformed

    private void BTFundacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFundacionesActionPerformed
        Fundaciones FN = new Fundaciones();
        FN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTFundacionesActionPerformed

    private void BTusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTusuariosActionPerformed
        Usuarios US = new Usuarios();
        US.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTFormularios;
    private javax.swing.JButton BTFundaciones;
    private javax.swing.JButton BTMascotasEnAdop;
    private javax.swing.JButton BTMascotas_Encontradas;
    private javax.swing.JButton BTcerrars;
    private javax.swing.JButton BTmascotas_perdidas;
    private javax.swing.JButton BTtendencia_responsable;
    private javax.swing.JButton BTusuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
