# Generated by Django 5.1.2 on 2024-10-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_estadoeconomico_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desparacitacion',
            new_name='Desparasitacion',
        ),
        migrations.RenameField(
            model_name='desparasitacion',
            old_name='conf_desparacitacion',
            new_name='conf_desparasitacion',
        ),
        migrations.RenameField(
            model_name='desparasitacion',
            old_name='fecha_desparacitacion',
            new_name='fecha_desparasitacion',
        ),
    ]
