# Generated by Django 5.1.2 on 2024-10-21 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_direccionusuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionusuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.perfilusuario'),
        ),
    ]
