# Generated by Django 5.1.2 on 2024-11-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_direccionusuario_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Esteriliacion',
            new_name='Esterilizacion',
        ),
    ]
