# Generated by Django 5.0.6 on 2024-11-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_esteriliacion_esterilizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fundacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.fundacion'),
        ),
    ]
