# Generated by Django 5.0.6 on 2024-11-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_mascota_fundacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomascota',
            name='descripcion',
            field=models.CharField(choices=[('gato', 'Gato'), ('perro', 'Perro'), ('otro', 'Otro')], max_length=50),
        ),
    ]
