# Generated by Django 5.0.6 on 2024-11-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_tipomascota_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tipo_edad',
            field=models.CharField(blank=True, choices=[('meses', 'Meses'), ('años', 'Años'), ('dias', 'Días')], max_length=50, null=True),
        ),
    ]
