# Generated by Django 5.0.6 on 2024-11-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_fundacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/fundaciones/'),
        ),
    ]
