# Generated by Django 5.0.6 on 2024-11-23 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_fundacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='razas',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.tipomascota'),
        ),
    ]
