# Generated by Django 5.0.6 on 2024-11-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_tipomascota_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomascota',
            name='descripcion',
            field=models.CharField(choices=[('gato', 'Gato'), ('perro', 'Perro'), ('otro', 'Otro')], max_length=50),
        ),
    ]
