# Generated by Django 5.1.2 on 2024-10-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudad',
            new_name='Provincia',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='ciudad',
            new_name='provincia',
        ),
    ]
