# Generated by Django 5.0.6 on 2024-10-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_comunamascota_descripcionmascota_estadomascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoeconomico',
            name='descripcion',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
