/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author digim
 */
public class Formularios extends javax.swing.JFrame {


    public Formularios() {
        setTitle("GESTIONAR FORMULARIOS");
        setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        
        Login login = new Login();
        txtUsuario.setText(login.TipoUsuario);
        cargarDatosTabla();
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("src/Img/Icono.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTEliminarFormu = new javax.swing.JButton();
        txtUsuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableFormulario = new javax.swing.JTable();
        BTModificarFormu = new javax.swing.JButton();
        BTVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtComentarios = new javax.swing.JTextField();
        BTSeleccionarForm = new javax.swing.JButton();
        ComboBoxEsFor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(94, 114, 228));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido:");

        BTEliminarFormu.setText("Eliminar Formularios");
        BTEliminarFormu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEliminarFormuActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtUsuario.setText("@NOMBRE ADMIN o Usuario");

        TableFormulario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Mascota", "Dueño", "Estado Formulario", "Comentarios"
            }
        ));
        jScrollPane2.setViewportView(TableFormulario);

        BTModificarFormu.setText("Modificar Formularios");
        BTModificarFormu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTModificarFormuActionPerformed(evt);
            }
        });

        BTVolver.setText("Volver");
        BTVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVolverActionPerformed(evt);
            }
        });

        jLabel2.setText("Estado Formulario");

        jLabel3.setText("Comentarios");

        BTSeleccionarForm.setText("Seleccionar Formulario");
        BTSeleccionarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSeleccionarFormActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTVolver)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(txtUsuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ComboBoxEsFor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BTEliminarFormu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BTModificarFormu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(BTSeleccionarForm)))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUsuario)
                                    .addComponent(jLabel1)))
                            .addComponent(BTVolver))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(BTSeleccionarForm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(ComboBoxEsFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(BTModificarFormu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(BTEliminarFormu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVolverActionPerformed
            Menu_Admin Menu_a = new Menu_Admin();
            Menu_a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BTVolverActionPerformed

    private void BTModificarFormuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTModificarFormuActionPerformed
        try {
            manejarModificacionFormulario();
        } catch (IOException ex) {
            Logger.getLogger(Formularios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTModificarFormuActionPerformed

    private void BTEliminarFormuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEliminarFormuActionPerformed
       manejarEliminacionFormulario();
    }//GEN-LAST:event_BTEliminarFormuActionPerformed

    private void BTSeleccionarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSeleccionarFormActionPerformed
        manejarSeleccionFormulario(); // Llama al método para manejar la selección del usuario
    }//GEN-LAST:event_BTSeleccionarFormActionPerformed

private String token = "a635c77de3de8cf58fa3e631b4e197b048670150";
private Map<Integer, String> estadosMap = new HashMap<>();


//-------------------------------------------------LISTAR DATOS FORMULARIOS---------------------------------------------------------- 
private void cargarEstadosFormulario() {
    String estadoFormularioUrl = "http://127.0.0.1:8000/api/estadoformulario/?format=json";
    
    try {
        // Obtener datos de los estados de formulario
        JSONArray estadoFormularioArray = obtenerDatosDeApi(estadoFormularioUrl);
        
        // Limpiar el ComboBox antes de agregar nuevos datos
        ComboBoxEsFor.removeAllItems();
        
        // Agregar los estados al ComboBox
        for (int i = 0; i < estadoFormularioArray.length(); i++) {
            JSONObject estadoFormularioObj = estadoFormularioArray.getJSONObject(i);
            String descripcionEstado = estadoFormularioObj.optString("descripcion", "N/A");
            ComboBoxEsFor.addItem(descripcionEstado);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar los estados del formulario.");
    }
}




private void cargarDatosTabla() {
    // Cargar los estados en el ComboBox
    cargarEstadosFormulario();
    
    String formularioUrl = "http://127.0.0.1:8000/api/formulario/?format=json";
    String usuariosUrl = "http://127.0.0.1:8000/api/perfilusuario/?format=json";
    String mascotasUrl = "http://127.0.0.1:8000/api/mascota/?format=json"; // URL para las mascotas
    DefaultTableModel model = (DefaultTableModel) TableFormulario.getModel();
    model.setRowCount(0); // Limpiar la tabla antes de cargar nuevos datos

    try {
        // Obtener datos de Formulario
        JSONArray formularioArray = obtenerDatosDeApi(formularioUrl);

        // Obtener datos de usuarios
        JSONArray usuariosArray = obtenerDatosDeApi(usuariosUrl);

        // Obtener datos de mascotas
        JSONArray mascotasArray = obtenerDatosDeApi(mascotasUrl);

        // Crear un mapa para relacionar mascota ID con su formulario
        Map<Integer, JSONObject> mascotaFormularioMap = new HashMap<>();
        for (int j = 0; j < formularioArray.length(); j++) {
            JSONObject formulario = formularioArray.getJSONObject(j);
            JSONObject mascota = formulario.optJSONObject("mascota");
            if (mascota != null) {
                int mascotaId = mascota.getInt("id");
                mascotaFormularioMap.put(mascotaId, formulario);
            }
        }

        // Procesar datos de las mascotas
        for (int i = 0; i < mascotasArray.length(); i++) {
            JSONObject mascotaObj = mascotasArray.getJSONObject(i);
            int mascotaId = mascotaObj.getInt("id");

            // Verificar si la mascota tiene un formulario asociado
            JSONObject formularioAsociado = mascotaFormularioMap.getOrDefault(mascotaId, null);

            if (formularioAsociado != null) {
                // Obtener datos del formulario
                int formularioId = formularioAsociado.getInt("id");
                String comentarios = formularioAsociado.optString("comentarios", "N/A");
                JSONObject estadoFormularioObj = formularioAsociado.optJSONObject("estado_formulario");
                String estadoFormulario = estadoFormularioObj != null ? estadoFormularioObj.optString("descripcion", "N/A") : "N/A";

                // Obtener datos del dueño de la mascota
                JSONObject usuarioObj = mascotaObj.optJSONObject("usuario");
                String nombreUsuario = "N/A";
                if (usuarioObj != null) {
                    JSONObject usuarioDjango = usuarioObj.optJSONObject("usuario_django");
                    String firstName = usuarioDjango != null ? usuarioDjango.optString("first_name", "N/A") : "N/A";
                    String lastName = usuarioDjango != null ? usuarioDjango.optString("last_name", "N/A") : "N/A";
                    nombreUsuario = firstName + " " + lastName;
                }

                // Añadir datos a la tabla
                String nombreMascota = mascotaObj.optString("nombre", "N/A");
                model.addRow(new Object[]{formularioId, nombreMascota, nombreUsuario, estadoFormulario, comentarios});
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos de las APIs.");
    }
}





// Método para obtener datos de la API
private JSONArray obtenerDatosDeApi(String urlString) throws IOException, JSONException {
    URL url = new URL(urlString);
    HttpURLConnection connection = (HttpURLConnection) url.openConnection();
    connection.setRequestMethod("GET");
    connection.setRequestProperty("Authorization", "Token " + token);
    connection.connect();

    int responseCode = connection.getResponseCode();
    if (responseCode == HttpURLConnection.HTTP_OK) {
        BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder response = new StringBuilder();
        String inputLine;
        while ((inputLine = in.readLine()) != null) {
            response.append(inputLine);
        }
        in.close();
        return new JSONArray(response.toString());
    } else {
        throw new IOException("Error en la conexión. Código de respuesta: " + responseCode);
    }
}




// Método para procesar las mascotas
private Map<Integer, String> procesarMascotas(JSONArray mascotasArray) {
    Map<Integer, String> mascotasMap = new HashMap<>();
    try {
        for (int i = 0; i < mascotasArray.length(); i++) {
            JSONObject mascotaObj = mascotasArray.getJSONObject(i);
            int idUsuario = mascotaObj.optJSONObject("usuario") != null ? mascotaObj.optJSONObject("usuario").optInt("id", -1) : -1;
            String nombreMascota = mascotaObj.optString("nombre", "N/A");
            
            // Guardar el nombre de la mascota asociado al ID del usuario
            if (idUsuario != -1) {
                mascotasMap.put(idUsuario, nombreMascota);
            }

            // Opcional: Mostrar en consola
            System.out.println("ID Usuario: " + idUsuario + ", Mascota: " + nombreMascota);
        }
    } catch (JSONException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al procesar datos de mascotas.");
    }
    return mascotasMap;
}

private Map<Integer, String> procesarDirecciones(JSONArray direccionesArray) {
    Map<Integer, String> direccionesMap = new HashMap<>();
    try {
        for (int i = 0; i < direccionesArray.length(); i++) {
            JSONObject direccionObj = direccionesArray.getJSONObject(i);
            int userId = direccionObj.getInt("id"); // ID del usuario asociado a la dirección
            String calle = direccionObj.optString("calle", "N/A");

            // Obtener los datos anidados de comuna, provincia, región y país
            JSONObject comunaObj = direccionObj.optJSONObject("comuna");
            String comunaNombre = "N/A";
            String provinciaNombre = "N/A";
            String regionNombre = "N/A";
            String paisNombre = "N/A";

            if (comunaObj != null) {
                comunaNombre = comunaObj.optString("nombre", "N/A");

                JSONObject provinciaObj = comunaObj.optJSONObject("provincia");
                if (provinciaObj != null) {
                    provinciaNombre = provinciaObj.optString("nombre", "N/A");

                    JSONObject regionObj = provinciaObj.optJSONObject("region");
                    if (regionObj != null) {
                        regionNombre = regionObj.optString("nombre", "N/A");

                        JSONObject paisObj = regionObj.optJSONObject("pais");
                        if (paisObj != null) {
                            paisNombre = paisObj.optString("nombre", "N/A");
                        }
                    }
                }
            }

            // Formatear la dirección completa
            String direccionCompleta = calle + ", " + comunaNombre + ", " + provinciaNombre + ", " + regionNombre + ", " + paisNombre;

            // Guardar la dirección asociada al ID del usuario
            direccionesMap.put(userId, direccionCompleta);

            // Opcional: Mostrar en consola
            System.out.println("ID Usuario: " + userId + ", Dirección Completa: " + direccionCompleta);
        }
    } catch (JSONException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al procesar datos de direcciones.");
    }
    return direccionesMap;
}
//-------------------------------------------------FIN LISTAR DATOS FORMULARIO------------------------------------------------------
    

//-------------------------------------------------INICIO MODIFICAR FORMULARIO-----------------------------------------------------
// Método para modificar el comentario del formulario utilizando los datos seleccionados
private void modificarComentarioFormularioSeleccionado(int formularioId) throws IOException {
    // Obtener el nuevo comentario desde el campo de texto
    String nuevoComentario = txtComentarios.getText();  // Suponiendo que tienes un campo de texto para el comentario

    // Verificar si el comentario está vacío
    if (nuevoComentario.isEmpty()) {
        JOptionPane.showMessageDialog(null, "El comentario no puede estar vacío.");
        return;
    }

    // URL para actualizar solo el comentario del formulario
    String urlComentarioFormulario = "http://127.0.0.1:8000/formulario/" + formularioId + "/";

    // Crear el JSON para la actualización
    JSONObject datosActualizados = new JSONObject();
    datosActualizados.put("comentarios", nuevoComentario);  // Enviar solo el nuevo comentario

    // Imprimir por consola cómo quedarán los datos antes de enviarlos
    System.out.println("Datos a enviar para modificar el comentario del formulario:");
    System.out.println(datosActualizados.toString(4));  // Usar el formato 'pretty print' con 4 espacios de indentación

    // Realizar la actualización
    try {
        HttpURLConnection connection = (HttpURLConnection) new URL(urlComentarioFormulario).openConnection();
        connection.setRequestMethod("PUT");
        connection.setRequestProperty("Authorization", "Token " + token);  // Usar tu token de autorización
        connection.setRequestProperty("Content-Type", "application/json");
        connection.setRequestProperty("Accept", "application/json");
        connection.setDoOutput(true);

        // Enviar los datos
        try (OutputStream os = connection.getOutputStream()) {
            byte[] input = datosActualizados.toString().getBytes("utf-8");
            os.write(input, 0, input.length);
        }

        // Obtener el código de respuesta y verificar la respuesta
        int responseCode = connection.getResponseCode();
        System.out.println("Código de respuesta HTTP: " + responseCode);

        // Leer la respuesta
        StringBuilder responseMessage = new StringBuilder();
        try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                responseMessage.append(inputLine);
            }
        }

        // Imprimir el cuerpo de la respuesta para ver detalles
        System.out.println("Respuesta de la API: " + responseMessage.toString());

        // Verificar si la respuesta es exitosa
        if (responseCode == HttpURLConnection.HTTP_OK) {
            System.out.println("Comentario del formulario modificado correctamente.");
            JOptionPane.showMessageDialog(null, "Comentario del formulario modificado correctamente.");
            cargarDatosTabla();  // Recargar la tabla para reflejar los cambios
        } else {
            System.err.println("Error al modificar comentario del formulario. Código de respuesta: " + responseCode);
            JOptionPane.showMessageDialog(null, "Error al modificar comentario del formulario.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al modificar comentario del formulario.");
    }
}



// Método para modificar el estado del formulario utilizando los datos seleccionados
private void modificarEstadoFormularioSeleccionado(int formularioId) throws IOException {
    // Obtener el estado seleccionado en el ComboBox
    String estadoSeleccionado = (String) ComboBoxEsFor.getSelectedItem();
    System.out.println(estadoSeleccionado);
    int estadoId = obtenerIdEstadoDesdeDescripcion(estadoSeleccionado);  // Método para obtener el ID del estado seleccionado
    System.out.println(estadoId);
    if (estadoId == -1) {
        JOptionPane.showMessageDialog(null, "Estado seleccionado no válido.");
        return;
    }

    // URL para actualizar solo el estado del formulario
    String urlEstadoFormulario = "http://127.0.0.1:8000/formularios/" + formularioId + "/estado/";

    // Crear el JSON para la actualización
    JSONObject datosActualizados = new JSONObject();
    datosActualizados.put("estado_formulario", estadoId);  // Enviar solo el ID del estado

    // Imprimir por consola cómo quedarán los datos antes de enviarlos
    System.out.println("Datos a enviar para modificar el estado del formulario:");
    System.out.println(datosActualizados.toString(4));  // Usar el formato 'pretty print' con 4 espacios de indentación

    // Realizar la actualización
    try {
        HttpURLConnection connection = (HttpURLConnection) new URL(urlEstadoFormulario).openConnection();
        connection.setRequestMethod("PUT");
        connection.setRequestProperty("Authorization", "Token " + token);  // Usar tu token de autorización
        connection.setRequestProperty("Content-Type", "application/json");
        connection.setRequestProperty("Accept", "application/json");
        connection.setDoOutput(true);

        // Enviar los datos
        try (OutputStream os = connection.getOutputStream()) {
            byte[] input = datosActualizados.toString().getBytes("utf-8");
            os.write(input, 0, input.length);
        }

        // Obtener el código de respuesta y verificar la respuesta
        int responseCode = connection.getResponseCode();
        System.out.println("Código de respuesta HTTP: " + responseCode);

        // Leer la respuesta
        StringBuilder responseMessage = new StringBuilder();
        try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                responseMessage.append(inputLine);
            }
        }

        // Imprimir el cuerpo de la respuesta para ver detalles
        System.out.println("Respuesta de la API: " + responseMessage.toString());

        // Verificar si la respuesta es exitosa
        if (responseCode == HttpURLConnection.HTTP_OK) {
            System.out.println("Estado del formulario modificado correctamente.");
            JOptionPane.showMessageDialog(null, "Estado del formulario modificado correctamente.");
            cargarDatosTabla();  // Recargar la tabla para reflejar los cambios
        } else {
            System.err.println("Error al modificar estado del formulario. Código de respuesta: " + responseCode);
            JOptionPane.showMessageDialog(null, "Error al modificar estado del formulario.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al modificar estado del formulario.");
    }
}




// Método para manejar la modificación del formulario desde la tabla
private void manejarModificacionFormulario() throws IOException {
    // Obtener la fila seleccionada de la tabla
    int filaSeleccionada = TableFormulario.getSelectedRow();

    if (filaSeleccionada != -1) {
        // Obtener el ID del formulario desde la tabla (suponiendo que el ID está en la columna 0)
        int formularioId = (int) TableFormulario.getValueAt(filaSeleccionada, 0);

        // Confirmación de modificación
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Está seguro de que desea modificar este formulario?",
            "Confirmar modificación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Confirmación para modificar solo el estado
            int estadoConfirmacion = JOptionPane.showConfirmDialog(
                null,
                "¿Desea modificar solo el estado del formulario?",
                "Modificar estado",
                JOptionPane.YES_NO_OPTION
            );
            if (estadoConfirmacion == JOptionPane.YES_OPTION) {
                modificarEstadoFormularioSeleccionado(formularioId);
            }

            // Confirmación para modificar el comentario
            int comentarioConfirmacion = JOptionPane.showConfirmDialog(
                null,
                "¿Desea modificar el comentario del formulario?",
                "Modificar comentario",
                JOptionPane.YES_NO_OPTION
            );
            if (comentarioConfirmacion == JOptionPane.YES_OPTION) {
                modificarComentarioFormularioSeleccionado(formularioId);
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione un formulario de la tabla.");
    }
}





// Método para obtener el ID del estado a partir de la descripción
private int obtenerIdEstadoDesdeDescripcion(String descripcionEstado) throws IOException {
    String estadoFormularioUrl = "http://127.0.0.1:8000/api/estadoformulario/?format=json";
    // Suponiendo que los estados provienen de una respuesta JSON
    JSONArray estadosArray = obtenerDatosDeApi(estadoFormularioUrl);  // Método ficticio para obtener datos

    // Llenamos el mapa con los datos
    for (int i = 0; i < estadosArray.length(); i++) {
        JSONObject estado = estadosArray.getJSONObject(i);
        int id = estado.getInt("id");
        String descripcion = estado.getString("descripcion");
        estadosMap.put(id, descripcion);  // Agregamos al mapa
    }

    
    // Realizar la búsqueda en el mapa de estados (debe estar cargado previamente)
    for (Map.Entry<Integer, String> entry : estadosMap.entrySet()) {
        if (entry.getValue().equals(descripcionEstado)) {
            
            return entry.getKey();
        }
    }
    System.out.println("Contenido del mapa de estados: " + estadosMap);

    return -1;  // Retorna -1 si no se encuentra el estado
}



//-------------------------------------------------FIN MODIFICAR FORMULARIO 

//-------------------------------------------------------INICIO ELIMINAR FORMULARIO--------------------------------------------------------


// Método para eliminar un Formulario a través de la API
private void eliminarFormulario(int formularioId) {
    String urlString = "http://127.0.0.1:8000/api/formulario/" + formularioId + "/"; // URL de la API para eliminar

    try {
        // Crear la URL y la conexión
        URL url = new URL(urlString);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();

        // Configurar el método DELETE y los encabezados
        connection.setRequestMethod("DELETE");
        connection.setRequestProperty("Authorization", "Token " + token);  // Token de autenticación
        connection.setRequestProperty("Accept", "application/json");

        // Conectar y obtener la respuesta
        connection.connect();
        int responseCode = connection.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_NO_CONTENT) {
            JOptionPane.showMessageDialog(null, "Formulario eliminado correctamente.");
            // Aquí puedes actualizar la tabla o hacer otras acciones
        } else {
            JOptionPane.showMessageDialog(null, "Error al eliminar el formulario. Código de respuesta: " + responseCode);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al eliminar formulario.");
    }
}

// Método común para manejar la eliminación de el Formulario
private void manejarEliminacionFormulario() {
    // Obtener la fila seleccionada
    int filaSeleccionada = TableFormulario.getSelectedRow();

    if (filaSeleccionada != -1) {
        // Obtener el ID del Formulario en la primera columna (suponiendo que el ID está en la columna 0)
        int FormularioId = (int) TableFormulario.getValueAt(filaSeleccionada, 0);

        // Mostrar un cuadro de confirmación para eliminar la Formulario
        int confirmacion = JOptionPane.showConfirmDialog(null, 
            "¿Está seguro de que desea eliminar esta mascota?", 
            "Confirmar eliminación", 
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            eliminarFormulario(FormularioId); // Llamar al método de eliminación
            cargarDatosTabla();  // Método para recargar la tabla si es necesario
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione una mascota de la tabla.");
    }
}

// Método para agregar el listener al hacer clic en la fila de la tabla
private void agregarListenerTabla() {
    TableFormulario.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
            manejarEliminacionFormulario(); // Llamar al método común
        }
    });
}

//-------------------------------------------------------FIN ELIMINAR FORMULARIO--------------------------------------------------------








//------------------------------------------------------INICIO SELECCIONAR FORMULARIO---------------------------------------------------
// Método para seleccionar un formulario y cargar sus datos desde la API
private void seleccionarFormulario(int formularioId) {
    String urlFormulario = "http://127.0.0.1:8000/api/formulario/" + formularioId + "/"; // URL de la API para obtener datos del formulario
    String urlEstadosFormulario = "http://127.0.0.1:8000/api/estadoformulario/?format=json"; // URL para obtener estados de formulario

    try {
        // Obtener los datos del formulario
        JSONObject jsonResponse = obtenerObjetoDeApi(urlFormulario);

        // Obtener el estado actual del formulario como objeto JSON
        String estadoFormulario = "N/A";
        JSONObject estadoFormularioObj = jsonResponse.optJSONObject("estado_formulario");
        if (estadoFormularioObj != null) {
            estadoFormulario = estadoFormularioObj.optString("descripcion", "N/A");
        }

        // Cargar el estado actual en el ComboBox
        cargarEstadosFormulario(urlEstadosFormulario, estadoFormulario);

        // Obtener los comentarios del formulario
        String comentarios = jsonResponse.optString("comentarios", "N/A");

        // Mostrar los datos en los campos correspondientes
        ComboBoxEsFor.setSelectedItem(estadoFormulario);
        txtComentarios.setText(comentarios);
        System.out.println(estadoFormulario);
        System.out.println(comentarios);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al seleccionar formulario.");
    }
}

// Método para cargar los estados en el ComboBox
private void cargarEstadosFormulario(String urlEstados, String estadoActual) {
    try {
        // Obtener los estados desde la API
        JSONArray estadosArray = obtenerDatosDeApi(urlEstados);

        // Limpiar el ComboBox antes de agregar los estados
        ComboBoxEsFor.removeAllItems();

        // Agregar los estados al ComboBox
        for (int i = 0; i < estadosArray.length(); i++) {
            JSONObject estado = estadosArray.getJSONObject(i);
            String descripcion = estado.optString("descripcion", "N/A");

            ComboBoxEsFor.addItem(descripcion);

            // Si el estado es el actual, seleccionarlo
            if (descripcion.equals(estadoActual)) {
                ComboBoxEsFor.setSelectedItem(descripcion);
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar los estados del formulario.");
    }
}

// Método para manejar la selección del formulario en la tabla y cargar los datos
private void manejarSeleccionFormulario() {
    // Obtener la fila seleccionada
    int filaSeleccionada = TableFormulario.getSelectedRow();

    if (filaSeleccionada != -1) {
        // Obtener el ID del formulario en la primera columna (suponiendo que el ID está en la columna 0)
        int formularioId = (int) TableFormulario.getValueAt(filaSeleccionada, 0);

        // Confirmación de selección
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Está seguro de que desea cargar los datos de este formulario?",
            "Confirmar selección",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                // Llamar al método para cargar los datos del formulario
                seleccionarFormulario(formularioId);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al manejar la selección del formulario.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione un formulario de la tabla.");
    }
}

// Método para obtener un objeto JSON desde una API
private JSONObject obtenerObjetoDeApi(String urlString) throws IOException, JSONException {
    URL url = new URL(urlString);
    HttpURLConnection connection = (HttpURLConnection) url.openConnection();
    connection.setRequestMethod("GET");
    connection.setRequestProperty("Authorization", "Token " + token);
    connection.setRequestProperty("Accept", "application/json");
    connection.connect();

    int responseCode = connection.getResponseCode();
    if (responseCode == HttpURLConnection.HTTP_OK) {
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder response = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            response.append(line);
        }
        reader.close();
        return new JSONObject(response.toString());
    } else {
        throw new IOException("Error en la conexión. Código de respuesta: " + responseCode);
    }
}





//-----------------------------------------------------FIN SELECCIONAR FORMULARIO-----------------------------------------------------






    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formularios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTEliminarFormu;
    private javax.swing.JButton BTModificarFormu;
    private javax.swing.JButton BTSeleccionarForm;
    private javax.swing.JButton BTVolver;
    private javax.swing.JComboBox<String> ComboBoxEsFor;
    private javax.swing.JTable TableFormulario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtComentarios;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
