/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author digim
 */
public class Mascotas_Adoptadas extends javax.swing.JFrame {


    public Mascotas_Adoptadas() {
        setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        
        Login login = new Login();
        txtUsuario.setText(login.TipoUsuario);
        cargarDatosTabla(); // Llamamos al método para cargar datos de la API en la tabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTEliminarMasAdop = new javax.swing.JButton();
        txtUsuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaMascotasAdoptadas = new javax.swing.JTable();
        BTModificarMasAdop = new javax.swing.JButton();
        BTVolver = new javax.swing.JButton();
        txtNombreMascota = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtEstadoMascota = new javax.swing.JTextField();
        BTSeleccionarMasAdop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido:");

        BTEliminarMasAdop.setText("Eliminar Mascota Adoptada");
        BTEliminarMasAdop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEliminarMasAdopActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtUsuario.setText("@NOMBRE ADMIN o Usuario");

        TablaMascotasAdoptadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre Mascota", "Dueño", "Estado Mascota"
            }
        ));
        jScrollPane2.setViewportView(TablaMascotasAdoptadas);

        BTModificarMasAdop.setText("Modificar Mascota Adoptada");
        BTModificarMasAdop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTModificarMasAdopActionPerformed(evt);
            }
        });

        BTVolver.setText("Volver");
        BTVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVolverActionPerformed(evt);
            }
        });

        BTSeleccionarMasAdop.setText("Seleccionar Mascota Adoptada");
        BTSeleccionarMasAdop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSeleccionarMasAdopActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Mascota");

        jLabel3.setText("Dueño");

        jLabel4.setText("Estado Mascota");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTVolver)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(txtUsuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BTEliminarMasAdop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BTModificarMasAdop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(45, 45, 45))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BTSeleccionarMasAdop)
                                        .addGap(83, 83, 83))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNombreMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtUsername)
                                    .addComponent(txtEstadoMascota))
                                .addGap(65, 65, 65)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario)
                            .addComponent(jLabel1)))
                    .addComponent(BTVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTSeleccionarMasAdop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstadoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(BTModificarMasAdop, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(BTEliminarMasAdop, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVolverActionPerformed
            Menu_Admin Menu_a = new Menu_Admin();
            Menu_a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BTVolverActionPerformed

    private void BTModificarMasAdopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTModificarMasAdopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTModificarMasAdopActionPerformed

    private void BTEliminarMasAdopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEliminarMasAdopActionPerformed
     manejarEliminacionMascota();
    }//GEN-LAST:event_BTEliminarMasAdopActionPerformed

    private void BTSeleccionarMasAdopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSeleccionarMasAdopActionPerformed
     manejarSeleccionMascota(); // Llama al método para manejar la selección del usuario
    }//GEN-LAST:event_BTSeleccionarMasAdopActionPerformed
  
private String token = "847c45faa3fe195e77a83ac0229e88494461e3aa";
    
//--------------------------------------------------------INICIO LISTAR DATOS-------------------------------------------------------------------------
private void cargarDatosTabla() {
    String mascotasUrl = "http://127.0.0.1:8000/api/mascota/?format=json";
    String usuariosUrl = "http://127.0.0.1:8000/api/perfilusuario/?format=json";
    DefaultTableModel model = (DefaultTableModel) TablaMascotasAdoptadas.getModel();
    model.setRowCount(0);

    try {
        // Obtener datos de mascotas
        JSONArray mascotasArray = obtenerDatosDeApi(mascotasUrl);

        // Obtener y procesar datos de usuarios
        JSONArray usuariosArray = obtenerDatosDeApi(usuariosUrl);
        Map<Integer, String> usuariosMap = procesarUsuarios(usuariosArray);

        // Procesar datos de mascotas
        for (int i = 0; i < mascotasArray.length(); i++) {
            JSONObject mascota = mascotasArray.getJSONObject(i);

            int idMascota = mascota.getInt("id");
            String nombreMascota = mascota.optString("nombre", "N/A");

            // Obtener la información del usuario (el objeto 'usuario' dentro de 'mascota')
            JSONObject usuario = mascota.optJSONObject("usuario");
            int idUsuario = usuario != null ? usuario.optInt("id", -1) : -1;  // Extraemos el 'id' del usuario
            

            // Obtener el username del usuario usando el mapa de usuarios
            String nombreUsuario = usuariosMap.getOrDefault(idUsuario, "N/A");


            JSONObject estadoMascota = mascota.optJSONObject("estado_mascota");
            String estado = estadoMascota != null ? estadoMascota.optString("descripcion", "N/A") : "N/A";

            if (estado.equals("adoptado")) {
                model.addRow(new Object[]{idMascota, nombreMascota, nombreUsuario, estado});
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos de las APIs.");
    }
}


// Método para obtener datos de la API
    private JSONArray obtenerDatosDeApi(String urlString) throws IOException, JSONException {
        URL url = new URL(urlString);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("GET");
        connection.setRequestProperty("Authorization", "Token " + token);
        connection.connect();

        int responseCode = connection.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_OK) {
            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            StringBuilder response = new StringBuilder();
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();
            return new JSONArray(response.toString());
        } else {
            throw new IOException("Error en la conexión. Código de respuesta: " + responseCode);
        }
    }


private Map<Integer, String> procesarUsuarios(JSONArray usuariosArray) {
    Map<Integer, String> usuariosMap = new HashMap<>();
    try {
        // Recorrer todos los usuarios en el JSONArray
        for (int i = 0; i < usuariosArray.length(); i++) {
            JSONObject usuario = usuariosArray.getJSONObject(i);

            int id = usuario.optInt("id", -1);
            JSONObject usuarioDjango = usuario.optJSONObject("usuario_django");
            String username = usuarioDjango != null ? usuarioDjango.optString("username", "N/A") : "N/A";

            // Almacenar en el mapa
            usuariosMap.put(id, username);

            // Opcional: Mostrar en consola
            System.out.println("ID: " + id + ", Username: " + username);
        }
    } catch (JSONException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al procesar datos del JSONArray.");
    }
    return usuariosMap;
}





//-------------------------------------------------------FIN LISTAR DATOS---------------------------------------------------------------------

//-------------------------------------------------------INICIO ELIMINAR MASCOTA ADOPTADA-----------------------------------------------------
// Método para eliminar una mascota a través de la API
private void eliminarMascota(int mascotaId) {
    String urlString = "http://127.0.0.1:8000/api/mascota/" + mascotaId + "/"; // URL de la API para eliminar

    try {
        // Crear la URL y la conexión
        URL url = new URL(urlString);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();

        // Configurar el método DELETE y los encabezados
        connection.setRequestMethod("DELETE");
        connection.setRequestProperty("Authorization", "Token " + token);  // Token de autenticación
        connection.setRequestProperty("Accept", "application/json");

        // Conectar y obtener la respuesta
        connection.connect();
        int responseCode = connection.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_NO_CONTENT) {
            JOptionPane.showMessageDialog(null, "Mascota eliminada correctamente.");
            // Aquí puedes actualizar la tabla o hacer otras acciones
        } else {
            JOptionPane.showMessageDialog(null, "Error al eliminar mascota. Código de respuesta: " + responseCode);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al eliminar mascota.");
    }
}

// Método común para manejar la eliminación de la mascota
private void manejarEliminacionMascota() {
    // Obtener la fila seleccionada
    int filaSeleccionada = TablaMascotasAdoptadas.getSelectedRow();

    if (filaSeleccionada != -1) {
        // Obtener el ID de la mascota en la primera columna (suponiendo que el ID está en la columna 0)
        int mascotaId = (int) TablaMascotasAdoptadas.getValueAt(filaSeleccionada, 0);

        // Mostrar un cuadro de confirmación para eliminar la mascota
        int confirmacion = JOptionPane.showConfirmDialog(null, 
            "¿Está seguro de que desea eliminar esta mascota?", 
            "Confirmar eliminación", 
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            eliminarMascota(mascotaId); // Llamar al método de eliminación
            cargarDatosTabla();  // Método para recargar la tabla si es necesario
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione una mascota de la tabla.");
    }
}

// Método para agregar el listener al hacer clic en la fila de la tabla
private void agregarListenerTabla() {
    TablaMascotasAdoptadas.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
            manejarEliminacionMascota(); // Llamar al método común
        }
    });
}

//-------------------------------------------------------FIN ELIMINAR MASCOTA ADOPTADA--------------------------------------------------------

//--------------------------------------------------------INICIO SELECCION MASCOTA ADOPTADA-------------------------------------------------------------
// Método para seleccionar una mascota y cargar sus datos desde la API
private void seleccionarMascota(int mascotaId) {
    String urlString = "http://127.0.0.1:8000/api/mascota/" + mascotaId + "/"; // URL de la API para obtener datos de la mascota

    try {
        // Crear la URL y la conexión
        URL url = new URL(urlString);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();

        // Configurar el método GET y los encabezados
        connection.setRequestMethod("GET");
        connection.setRequestProperty("Authorization", "Token " + token);  // Token de autenticación
        connection.setRequestProperty("Accept", "application/json");

        // Conectar y obtener la respuesta
        connection.connect();
        int responseCode = connection.getResponseCode();

        if (responseCode == HttpURLConnection.HTTP_OK) {
            // Leer la respuesta de la API
            BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            StringBuilder response = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                response.append(line);
            }

            // Convertir la respuesta en un JSONObject
            JSONObject jsonResponse = new JSONObject(response.toString());

            // Procesar estado de la mascota como objeto JSON
            String estadoMascota = "N/A";
            JSONObject estadoMascotaObj = jsonResponse.optJSONObject("estado_mascota");
            if (estadoMascotaObj != null) {
                estadoMascota = estadoMascotaObj.optString("descripcion", "N/A");
            }

            // Filtrar solo si el estado de la mascota es "Adoptada"
            if (estadoMascota.equals("adoptado")) {
                // Obtener los datos básicos de la mascota
                String nombreMascota = jsonResponse.optString("nombre", "N/A");
                String username = jsonResponse.optString("username", "N/A");

                // Mostrar los datos en los campos correspondientes
                txtNombreMascota.setText(nombreMascota);
                txtUsername.setText(username);
                txtEstadoMascota.setText(estadoMascota);

                // Deshabilitar los campos que no deben ser modificados
                txtNombreMascota.setEditable(false);
                txtNombreMascota.setBackground(Color.GRAY);

                txtUsername.setEditable(false);
                txtUsername.setBackground(Color.GRAY);

                txtEstadoMascota.setEditable(false);
                txtEstadoMascota.setBackground(Color.GRAY);
            } else {
                JOptionPane.showMessageDialog(null, "La mascota seleccionada no está adoptada.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al obtener datos de la mascota.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al seleccionar mascota.");
    }
}

// Método para manejar la selección de la mascota en la tabla y cargar los datos
private void manejarSeleccionMascota() {
    // Obtener la fila seleccionada
    int filaSeleccionada = TablaMascotasAdoptadas.getSelectedRow();

    if (filaSeleccionada != -1) {
        // Obtener el ID de la mascota en la primera columna (suponiendo que el ID está en la columna 0)
        int mascotaId = (int) TablaMascotasAdoptadas.getValueAt(filaSeleccionada, 0);

        // Confirmación de selección
        int confirmacion = JOptionPane.showConfirmDialog(null,
            "¿Está seguro de que desea cargar los datos de esta mascota?",
            "Confirmar selección",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            seleccionarMascota(mascotaId); // Llamar al método para cargar los datos
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione una mascota de la tabla.");
    }
}

//--------------------------------------------------------FIN SELECCION MASCOTA ADOPTADA-------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mascotas_Adoptadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mascotas_Adoptadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mascotas_Adoptadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mascotas_Adoptadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mascotas_Adoptadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTEliminarMasAdop;
    private javax.swing.JButton BTModificarMasAdop;
    private javax.swing.JButton BTSeleccionarMasAdop;
    private javax.swing.JButton BTVolver;
    private javax.swing.JTable TablaMascotasAdoptadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtEstadoMascota;
    private javax.swing.JTextField txtNombreMascota;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
