/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author digim
 */
public class Menu_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu_Admin() {
        setTitle("MENU DE SELECCIÓN");
        setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        
        Login login = new Login();
        txtUsuario.setText(login.TipoUsuario);
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("src/Img/Icono.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTMascotasEnAdop = new javax.swing.JButton();
        BTMascotas_Encontradas = new javax.swing.JButton();
        BTFicha_Medica = new javax.swing.JButton();
        BTmascotas_perdidas = new javax.swing.JButton();
        txtUsuario = new javax.swing.JLabel();
        BTcerrars = new javax.swing.JButton();
        BTFormularios = new javax.swing.JButton();
        BTFundaciones = new javax.swing.JButton();
        BTusuarios = new javax.swing.JButton();
        BTmascotas_Adoptadas = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(94, 114, 228));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido:");

        BTMascotasEnAdop.setText("Ir a Mascotas en Adopcion");
        BTMascotasEnAdop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMascotasEnAdopActionPerformed(evt);
            }
        });

        BTMascotas_Encontradas.setText("Ir a Mascotas Encontradas");
        BTMascotas_Encontradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMascotas_EncontradasActionPerformed(evt);
            }
        });

        BTFicha_Medica.setText("Ir a Ficha Medica");
        BTFicha_Medica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFicha_MedicaActionPerformed(evt);
            }
        });

        BTmascotas_perdidas.setText("Ir a Mascotas Perdidas");
        BTmascotas_perdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTmascotas_perdidasActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtUsuario.setText("@NOMBRE ADMIN");

        BTcerrars.setText("Cerrar Sesion");
        BTcerrars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcerrarsActionPerformed(evt);
            }
        });

        BTFormularios.setText("Ir a Formularios");
        BTFormularios.setMaximumSize(new java.awt.Dimension(93, 23));
        BTFormularios.setMinimumSize(new java.awt.Dimension(93, 23));
        BTFormularios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFormulariosActionPerformed(evt);
            }
        });

        BTFundaciones.setText("Ir a Fundaciones");
        BTFundaciones.setMaximumSize(new java.awt.Dimension(93, 23));
        BTFundaciones.setMinimumSize(new java.awt.Dimension(93, 23));
        BTFundaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTFundacionesActionPerformed(evt);
            }
        });

        BTusuarios.setText("Ir a Usuarios");
        BTusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTusuariosActionPerformed(evt);
            }
        });

        BTmascotas_Adoptadas.setText("Ir a Mascotas Adoptadas");
        BTmascotas_Adoptadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTmascotas_AdoptadasActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTcerrars)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTmascotas_perdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTMascotas_Encontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTmascotas_Adoptadas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTMascotasEnAdop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTFicha_Medica, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTFormularios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTFundaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BTcerrars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsuario))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTmascotas_Adoptadas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTmascotas_perdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTFundaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTMascotas_Encontradas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTFicha_Medica, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTFormularios, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTMascotasEnAdop, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTMascotas_EncontradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMascotas_EncontradasActionPerformed
        Mascotas_Encontradas ME = new Mascotas_Encontradas();
        ME.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTMascotas_EncontradasActionPerformed

    private void BTFicha_MedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFicha_MedicaActionPerformed
        Ficha_Medica TR = new Ficha_Medica();
        TR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTFicha_MedicaActionPerformed

    private void BTmascotas_perdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTmascotas_perdidasActionPerformed

        Mascotas_Perdidas MP = new Mascotas_Perdidas();
        MP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTmascotas_perdidasActionPerformed

    private void BTcerrarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcerrarsActionPerformed
        Login lo= new Login();
        lo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTcerrarsActionPerformed

    private void BTFormulariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFormulariosActionPerformed
        Formularios FM = new Formularios();
        FM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTFormulariosActionPerformed

    private void BTMascotasEnAdopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMascotasEnAdopActionPerformed
        Mascotas_en_Adopcion Mas = new Mascotas_en_Adopcion();
        Mas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTMascotasEnAdopActionPerformed

    private void BTFundacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTFundacionesActionPerformed
        Fundaciones FN = new Fundaciones();
        FN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTFundacionesActionPerformed

    private void BTusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTusuariosActionPerformed
        Usuarios US = new Usuarios();
        US.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTusuariosActionPerformed

    private void BTmascotas_AdoptadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTmascotas_AdoptadasActionPerformed
        Mascotas_Adoptadas Mascotas_Adoptadas = new Mascotas_Adoptadas();
        Mascotas_Adoptadas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTmascotas_AdoptadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTFicha_Medica;
    private javax.swing.JButton BTFormularios;
    private javax.swing.JButton BTFundaciones;
    private javax.swing.JButton BTMascotasEnAdop;
    private javax.swing.JButton BTMascotas_Encontradas;
    private javax.swing.JButton BTcerrars;
    private javax.swing.JButton BTmascotas_Adoptadas;
    private javax.swing.JButton BTmascotas_perdidas;
    private javax.swing.JButton BTusuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
