/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



package Vista;

import java.awt.Color;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JOptionPane;
import org.json.Cookie;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import org.json.JSONException;

/**
 *
 * @author digim
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Usuarios() {
        setTitle("GESTIONAR USUARIOS");
        setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        
        Login login = new Login();
        txtUsuario.setText(login.TipoUsuario);
        cargarGeneros(ComboBoxEsGe);
        cargarEstadosEconomicos(ComboBoxEsEc);
        cargarDatosTabla(); // Llamamos al método para cargar datos de la API en la tabla
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon("src/Img/Icono.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTEliminarUS = new javax.swing.JButton();
        txtUsuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableUsuarios = new javax.swing.JTable();
        BTSeleccionarUS = new javax.swing.JButton();
        BTVolver = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BTModificarUS1 = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ComboBoxEsEc = new javax.swing.JComboBox<>();
        ComboBoxEsGe = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(94, 114, 228));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido:");

        BTEliminarUS.setText("Eliminar Usuarios");
        BTEliminarUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEliminarUSActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtUsuario.setText("@NOMBRE ADMIN");

        TableUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Rut", "Telefono", "Estado Economico", "Genero", "Pais", "Region", "Provincia", "Comuna", "Direccion"
            }
        ));
        TableUsuarios.setMinimumSize(new java.awt.Dimension(180, 180));
        TableUsuarios.setRowHeight(20);
        jScrollPane2.setViewportView(TableUsuarios);
        if (TableUsuarios.getColumnModel().getColumnCount() > 0) {
            TableUsuarios.getColumnModel().getColumn(0).setMaxWidth(100);
            TableUsuarios.getColumnModel().getColumn(3).setMinWidth(100);
            TableUsuarios.getColumnModel().getColumn(4).setMinWidth(100);
            TableUsuarios.getColumnModel().getColumn(5).setMinWidth(100);
            TableUsuarios.getColumnModel().getColumn(6).setMinWidth(100);
            TableUsuarios.getColumnModel().getColumn(8).setMinWidth(350);
            TableUsuarios.getColumnModel().getColumn(9).setMinWidth(200);
            TableUsuarios.getColumnModel().getColumn(10).setMinWidth(100);
            TableUsuarios.getColumnModel().getColumn(11).setMinWidth(100);
        }

        BTSeleccionarUS.setText("Seleccionar Usuario");
        BTSeleccionarUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSeleccionarUSActionPerformed(evt);
            }
        });

        BTVolver.setText("Volver");
        BTVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVolverActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Rut");

        jLabel4.setText("Telefono");

        jLabel5.setText("Estado Economico");

        jLabel6.setText("Genero");

        BTModificarUS1.setText("Modificar Usuario");
        BTModificarUS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTModificarUS1ActionPerformed(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        jLabel7.setText("Apellido");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre de Usuario");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jLabel9.setText("Email");

        ComboBoxEsEc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEsEcActionPerformed(evt);
            }
        });

        ComboBoxEsGe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEsGeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BTVolver)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(txtUsuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(57, 57, 57)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(BTSeleccionarUS)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtUsername)
                                            .addComponent(txtApellido)
                                            .addComponent(txtNombre)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9))
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmail)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtRut)
                                            .addComponent(ComboBoxEsEc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBoxEsGe, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BTEliminarUS, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTModificarUS1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario)
                            .addComponent(jLabel1)))
                    .addComponent(BTVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(BTSeleccionarUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(ComboBoxEsEc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ComboBoxEsGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(BTModificarUS1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BTEliminarUS, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVolverActionPerformed
            Menu_Admin Menu_a = new Menu_Admin();
            Menu_a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BTVolverActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BTSeleccionarUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSeleccionarUSActionPerformed
        manejarSeleccionUsuario(); // Llama al método para manejar la selección del usuario
    }//GEN-LAST:event_BTSeleccionarUSActionPerformed

    private void BTEliminarUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEliminarUSActionPerformed
        manejarEliminacionUsuario();
    }//GEN-LAST:event_BTEliminarUSActionPerformed

    private void BTModificarUS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTModificarUS1ActionPerformed
        manejarModificacionUsuario();
    }//GEN-LAST:event_BTModificarUS1ActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void ComboBoxEsEcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEsEcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEsEcActionPerformed

    private void ComboBoxEsGeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEsGeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEsGeActionPerformed

private int usuarioId; // Variable para almacenar la ID seleccionada
private String token = "8ffeb3f8e3edc9915795f7c57fb11b39b1dd96a2";
private String token2 = "a635c77de3de8cf58fa3e631b4e197b048670150";
private Map<Integer, String> generosMap = new HashMap<>();
private Map<Integer, String> estadosEconomicosMap = new HashMap<>();




//--------------------------------------------------------INICIO LISTAR DATOS-------------------------------------------------------------------------
private void cargarDatosTabla() {
    String usuariosUrl = "http://127.0.0.1:8000/api/perfilusuario/?format=json";
    String direccionesUrl = "http://127.0.0.1:8000/api/direccionusuario/?format=json";
    String estadosEconomicosUrl= "http://127.0.0.1:8000/api/estadoeconomico/?format=json";
    String generosUrl = "http://127.0.0.1:8000/api/genero/?format=json";
    DefaultTableModel model = (DefaultTableModel) TableUsuarios.getModel();
    model.setRowCount(0); // Limpiar la tabla antes de cargar nuevos datos

    try {
        // Obtener datos de usuarios
        JSONArray usuariosArray = obtenerDatosDeApi(usuariosUrl);

        // Obtener datos de direcciones
        JSONArray direccionesArray = obtenerDatosDeApi(direccionesUrl);

        // Crear un mapa para relacionar usuario ID con su dirección
        Map<Integer, String> direccionesMap = procesarDirecciones(direccionesArray);

        // Obtener y procesar datos de géneros
        JSONArray generosArray = obtenerDatosDeApi(generosUrl);
        generosMap = procesarGeneros(generosArray);

        // Obtener y procesar datos de estados económicos
        JSONArray estadosEconomicosArray = obtenerDatosDeApi(estadosEconomicosUrl);
        estadosEconomicosMap = procesarEstadosEconomicos(estadosEconomicosArray);

        // Procesar datos de usuarios
        for (int i = 0; i < usuariosArray.length(); i++) {
            JSONObject usuarioObj = usuariosArray.getJSONObject(i);
            JSONObject DireccionObj = direccionesArray.getJSONObject(i);
            int id = usuarioObj.getInt("id");
            String rut = usuarioObj.optString("rut", "N/A");
            String telefono = usuarioObj.optString("telefono", "N/A");

            // Procesar el estado económico
            JSONObject estadoEconomicoObj = usuarioObj.optJSONObject("estado_economico");
            String estadoEconomico = estadoEconomicoObj != null ? estadoEconomicoObj.optString("descripcion", "N/A") : "N/A";

            // Procesar género
            JSONObject generoObj = usuarioObj.optJSONObject("genero");
            String genero = generoObj != null ? generoObj.optString("descripcion", "N/A") : usuarioObj.optString("genero", "N/A");

            // Obtener datos del usuario Django
            JSONObject usuarioDjango = usuarioObj.optJSONObject("usuario_django");
            String firstName = usuarioDjango != null ? usuarioDjango.optString("first_name", "N/A") : "N/A";
            String lastName = usuarioDjango != null ? usuarioDjango.optString("last_name", "N/A") : "N/A";
            
            //Sacar La Calle
            String direccion = DireccionObj.optString("calle", "N/A");
            
            //Sacar la Comuna
            JSONObject ComunaObj = DireccionObj.optJSONObject("comuna");
            String comuna = ComunaObj != null ? ComunaObj.optString("nombre", "N/A") : "N/A";
   
            //Sacar La Provincia
            JSONObject ProvinciaObj = ComunaObj.optJSONObject("provincia");
            String Provincia = ProvinciaObj != null ? ProvinciaObj.optString("nombre", "N/A") : "N/A";
            
            //Sacar La Region
            JSONObject RegionObj = ProvinciaObj.optJSONObject("region");
            String Region = RegionObj != null ? RegionObj.optString("nombre", "N/A") : "N/A";
            
            //Sacar El Pais
            JSONObject PaisObj = RegionObj.optJSONObject("pais");
            String Pais = PaisObj != null ? PaisObj.optString("nombre", "N/A") : "N/A";

            
            // Añadir datos a la tabla
            model.addRow(new Object[]{id, firstName, lastName, rut, telefono, estadoEconomico, genero, Pais, Region, Provincia, comuna, direccion});
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar datos de las APIs.");
    }
}

// Método para cargar géneros en ComboBoxEsGe
public void cargarGeneros(JComboBox<String> comboBoxEsGe) {
    String apiUrl = "http://127.0.0.1:8000/api/genero/?format=json";
    
    try {
        // Obtener los datos de la API
        JSONArray generos = obtenerDatosDeApi(apiUrl);
        
        // Procesar los géneros y almacenarlos en un Map
        Map<Integer, String> generosMap = procesarGeneros(generos);

        // Limpiar y rellenar el ComboBox
        comboBoxEsGe.removeAllItems();
        for (String genero : generosMap.values()) {
            comboBoxEsGe.addItem(genero); // Añadir los géneros al ComboBox
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar géneros: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// Método para procesar los géneros
private Map<Integer, String> procesarGeneros(JSONArray generosArray) {
    Map<Integer, String> generosMap = new HashMap<>();
    try {
        // Recorrer todos los géneros en el JSONArray
        for (int i = 0; i < generosArray.length(); i++) {
            JSONObject genero = generosArray.getJSONObject(i);
            int id = genero.optInt("id", -1);
            String descripcion = genero.optString("descripcion", "N/A");

            // Almacenar en el mapa
            generosMap.put(id, descripcion);
        }
    } catch (JSONException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al procesar datos de géneros.");
    }
    return generosMap;
}


// Método para cargar estados económicos en ComboBoxEsEc
public void cargarEstadosEconomicos(JComboBox<String> comboBoxEsEc) {
    String apiUrl = "http://127.0.0.1:8000/api/estadoeconomico/?format=json";
    
    try {
        // Obtener los datos de la API
        JSONArray estadosEconomicos = obtenerDatosDeApi(apiUrl);
        
        // Procesar los estados económicos y almacenarlos en un Map
        Map<Integer, String> estadosEconomicosMap = procesarEstadosEconomicos(estadosEconomicos);

        // Limpiar y rellenar el ComboBox
        comboBoxEsEc.removeAllItems();
        for (String estado : estadosEconomicosMap.values()) {
            comboBoxEsEc.addItem(estado); // Añadir los estados económicos al ComboBox
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar estados económicos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// Método para procesar los estados económicos
private Map<Integer, String> procesarEstadosEconomicos(JSONArray estadosArray) {
    Map<Integer, String> estadosEconomicosMap = new HashMap<>();
    try {
        // Recorrer todos los estados económicos en el JSONArray
        for (int i = 0; i < estadosArray.length(); i++) {
            JSONObject estado = estadosArray.getJSONObject(i);
            int id = estado.optInt("id", -1);
            String descripcion = estado.optString("descripcion", "N/A");

            // Almacenar en el mapa
            estadosEconomicosMap.put(id, descripcion);
        }
    } catch (JSONException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al procesar datos de estados económicos.");
    }
    return estadosEconomicosMap;
}




// Método para obtener datos de la API
private JSONArray obtenerDatosDeApi(String urlString) throws IOException, JSONException {
    URL url = new URL(urlString);
    HttpURLConnection connection = (HttpURLConnection) url.openConnection();
    connection.setRequestMethod("GET");
    connection.setRequestProperty("Authorization", "Token " + token);
    //connection.setRequestProperty("Authorization", "Token " + token2);
    connection.connect();

    int responseCode = connection.getResponseCode();
    if (responseCode == HttpURLConnection.HTTP_OK) {
        BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder response = new StringBuilder();
        String inputLine;
        while ((inputLine = in.readLine()) != null) {
            response.append(inputLine);
        }
        in.close();
        return new JSONArray(response.toString());
    } else {
        throw new IOException("Error en la conexión. Código de respuesta: " + responseCode);
    }
}

private Map<Integer, String> procesarDirecciones(JSONArray direccionesArray) {
    Map<Integer, String> direccionesMap = new HashMap<>();
    try {
        for (int i = 0; i < direccionesArray.length(); i++) {
            JSONObject direccionObj = direccionesArray.getJSONObject(i);
            int userId = direccionObj.getInt("id"); // ID del usuario asociado a la dirección
            String calle = direccionObj.optString("calle", "N/A");

            // Obtener los datos anidados de comuna, provincia, región y país
            JSONObject comunaObj = direccionObj.optJSONObject("comuna");
            String comunaNombre = "N/A";
            String provinciaNombre = "N/A";
            String regionNombre = "N/A";
            String paisNombre = "N/A";

            if (comunaObj != null) {
                comunaNombre = comunaObj.optString("nombre", "N/A");

                JSONObject provinciaObj = comunaObj.optJSONObject("provincia");
                if (provinciaObj != null) {
                    provinciaNombre = provinciaObj.optString("nombre", "N/A");

                    JSONObject regionObj = provinciaObj.optJSONObject("region");
                    if (regionObj != null) {
                        regionNombre = regionObj.optString("nombre", "N/A");

                        JSONObject paisObj = regionObj.optJSONObject("pais");
                        if (paisObj != null) {
                            paisNombre = paisObj.optString("nombre", "N/A");
                        }
                    }
                }
            }

            // Formatear la dirección completa
            String direccionCompleta = calle + ", " + comunaNombre + ", " + provinciaNombre + ", " + regionNombre + ", " + paisNombre;

            // Guardar la dirección asociada al ID del usuario
            direccionesMap.put(userId, direccionCompleta);

            // Opcional: Mostrar en consola
            System.out.println("ID Usuario: " + userId + ", Dirección Completa: " + direccionCompleta);
        }
    } catch (JSONException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al procesar datos de direcciones.");
    }
    return direccionesMap;
}






//-------------------------------------------------------FIN LISTAR DATOS---------------------------------------------------------------------
    
    
//-------------------------------------------------------INICIO MODIFICAR------------------------------------------------//

private void modificarUsuario(int usuarioId) {
    String urlString = "http://127.0.0.1:8000/usuario/" + usuarioId + "/"; // URL de la API para modificar datos

    try {
        // Crear la URL y la conexión
        URL url = new URL(urlString);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();

        // Configurar el método PUT y los encabezados
        connection.setRequestMethod("PUT"); // Cambiar a "PATCH" si solo deseas actualizar algunos campos
        connection.setRequestProperty("Authorization", "Token " + token);  // Token de autenticación
        connection.setRequestProperty("Content-Type", "application/json; utf-8");
        connection.setRequestProperty("Accept", "application/json");
        connection.setDoOutput(true);



        // Crear el objeto JSON con los datos modificados
        JSONObject jsonData = new JSONObject();
        jsonData.put("usuario", new JSONObject()
                .put("first_name", txtNombre.getText())
                .put("last_name", txtApellido.getText())
                .put("username", txtUsername.getText())
                .put("email", txtEmail.getText()));
        jsonData.put("rut", txtRut.getText());
        jsonData.put("telefono", txtTelefono.getText());


        // Imprimir los datos antes de enviarlos
        System.out.println("Datos a enviar para modificar el usuario:");
        System.out.println(jsonData.toString(4));  // Usar el formato 'pretty print' con 4 espacios de indentación

        // Enviar los datos a la API
        try (OutputStream os = connection.getOutputStream()) {
            byte[] input = jsonData.toString().getBytes("utf-8");
            os.write(input, 0, input.length);
        }

        // Leer la respuesta de la API
        int responseCode = connection.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_OK || responseCode == HttpURLConnection.HTTP_NO_CONTENT) {
            System.out.println("Usuario modificado con éxito.");
            JOptionPane.showMessageDialog(null, "Usuario modificado con éxito.");
        } else {
            // Leer y mostrar el error desde la API
            BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getErrorStream(), "utf-8"));
            StringBuilder errorResponse = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                errorResponse.append(line.trim());
            }
            System.err.println("Error al modificar el usuario. Código de respuesta: " + responseCode);
            System.err.println("Detalles del error: " + errorResponse.toString());
            JOptionPane.showMessageDialog(null, "Error al modificar el usuario.");
        }
    } catch (Exception e) {
        e.printStackTrace(); // Mostrar el error completo en la consola
        JOptionPane.showMessageDialog(null, "Error al modificar el usuario.");
    }
}


// Método para obtener el ID del estado a partir de la descripción
private int obtenerIdEstadoDesdeDescripcion(String descripcionEstado) {
    // Realizar la búsqueda en el mapa de estados (debe estar cargado previamente)
    for (Map.Entry<Integer, String> entry : estadosEconomicosMap.entrySet()) {
        if (entry.getValue().equals(descripcionEstado)) {
            return entry.getKey();
            
        }
        
    }
    return -1;  // Retorna -1 si no se encuentra el estado
}

// Método para obtener el ID del género a partir de la descripción
private int obtenerIdGeneroDesdeDescripcion(String descripcionGenero) {
    // Realizar la búsqueda en el mapa de géneros (debe estar cargado previamente)
    for (Map.Entry<Integer, String> entry : generosMap.entrySet()) {
        if (entry.getValue().equals(descripcionGenero)) {
            return entry.getKey();
        }
        
        
    }
    
    return -1;  // Retorna -1 si no se encuentra el género
}
// Método para imprimir el mapa de géneros
private void imprimirMapaGeneros() {
    // Imprimir todas las claves y valores del mapa
    System.out.println("Mapa de géneros:");
    for (Map.Entry<Integer, String> entry : generosMap.entrySet()) {
        System.out.println("Género: " + entry.getKey() + ", ID: " + entry.getValue());
    }
}
// Método para modificar el género del usuario utilizando los datos seleccionados
private void modificarGeneroUsuarioSeleccionado(int usuarioId) {
    // Obtener el género seleccionado en el ComboBox
    String generoSeleccionado = (String) ComboBoxEsGe.getSelectedItem();
    int generoId = obtenerIdGeneroDesdeDescripcion(generoSeleccionado);  // Método para obtener el ID del género seleccionado
    System.out.println("NOMBRE "+ generoSeleccionado);
    System.out.println("ID: " + generoId);
    if (generoId == -1) {
        JOptionPane.showMessageDialog(null, "Género seleccionado no válido.");
        return;
    }

    // URL para actualizar solo el género del usuario
    String urlGeneroUsuario = "http://127.0.0.1:8000/perfiles/" + usuarioId + "/genero/";

    // Crear el JSON para la actualización
    JSONObject datosActualizados = new JSONObject();
    datosActualizados.put("genero", generoId);  // Enviar solo el ID del género

    // Imprimir por consola cómo quedarán los datos antes de enviarlos
    System.out.println("Datos a enviar para modificar el género del usuario:");
    System.out.println(datosActualizados.toString(4));  // Usar el formato 'pretty print' con 4 espacios de indentación

    // Realizar la actualización
    try {
        HttpURLConnection connection = (HttpURLConnection) new URL(urlGeneroUsuario).openConnection();
        connection.setRequestMethod("PUT");
        connection.setRequestProperty("Authorization", "Token " + token);
        connection.setRequestProperty("Content-Type", "application/json");
        connection.setRequestProperty("Accept", "application/json");
        connection.setDoOutput(true);

        // Enviar los datos
        try (OutputStream os = connection.getOutputStream()) {
            byte[] input = datosActualizados.toString().getBytes("utf-8");
            os.write(input, 0, input.length);
        }

        // Obtener el código de respuesta y verificar la respuesta
        int responseCode = connection.getResponseCode();
        System.out.println("Código de respuesta HTTP: " + responseCode);

        // Leer la respuesta
        StringBuilder responseMessage = new StringBuilder();
        try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                responseMessage.append(inputLine);
            }
        }

        // Imprimir el cuerpo de la respuesta para ver detalles
        System.out.println("Respuesta de la API: " + responseMessage.toString());

        // Verificar si la respuesta es exitosa
        if (responseCode == HttpURLConnection.HTTP_OK) {
            System.out.println("Género del usuario modificado correctamente.");
            JOptionPane.showMessageDialog(null, "Género del usuario modificado correctamente.");
            cargarDatosTabla();  // Recargar la tabla para reflejar los cambios
        } else {
            System.err.println("Error al modificar género del usuario. Código de respuesta: " + responseCode);
            JOptionPane.showMessageDialog(null, "Error al modificar género del usuario.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al modificar género del usuario.");
    }
}

// Método para modificar el estado económico del usuario utilizando los datos seleccionados
private void modificarEstadoEconomicoUsuarioSeleccionado(int usuarioId) {
    // Obtener el estado económico seleccionado en el ComboBox
    String estadoEconomicoSeleccionado = (String) ComboBoxEsEc.getSelectedItem();
    int estadoEconomicoId = obtenerIdEstadoDesdeDescripcion(estadoEconomicoSeleccionado);  // Método para obtener el ID del estado económico seleccionado
    System.out.println("NOMBRE "+ estadoEconomicoSeleccionado);
    System.out.println("ID: " + estadoEconomicoId);
    if (estadoEconomicoId == -1) {
        JOptionPane.showMessageDialog(null, "Estado económico seleccionado no válido.");
        return;
    }

    // URL para actualizar solo el estado económico del usuario
    String urlEstadoEconomicoUsuario = "http://127.0.0.1:8000/perfiles/" + usuarioId + "/estado-economico/";

    // Crear el JSON para la actualización
    JSONObject datosActualizados = new JSONObject();
    datosActualizados.put("estado_economico", estadoEconomicoId);  // Enviar solo el ID del estado económico
    // Imprimir por consola cómo quedarán los datos antes de enviarlos
    System.out.println("Datos a enviar para modificar el estado económico del usuario:");
    System.out.println(datosActualizados.toString(4));  // Usar el formato 'pretty print' con 4 espacios de indentación

    // Realizar la actualización
    try {
        HttpURLConnection connection = (HttpURLConnection) new URL(urlEstadoEconomicoUsuario).openConnection();
        connection.setRequestMethod("PUT");
        connection.setRequestProperty("Authorization", "Token " + token);
        connection.setRequestProperty("Content-Type", "application/json");
        connection.setRequestProperty("Accept", "application/json");
        connection.setDoOutput(true);

        // Enviar los datos
        try (OutputStream os = connection.getOutputStream()) {
            byte[] input = datosActualizados.toString().getBytes("utf-8");
            os.write(input, 0, input.length);
        }

        // Obtener el código de respuesta y verificar la respuesta
        int responseCode = connection.getResponseCode();
        System.out.println("Código de respuesta HTTP: " + responseCode);

        // Leer la respuesta
        StringBuilder responseMessage = new StringBuilder();
        try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                responseMessage.append(inputLine);
            }
        }

        // Imprimir el cuerpo de la respuesta para ver detalles
        System.out.println("Respuesta de la API: " + responseMessage.toString());

        // Verificar si la respuesta es exitosa
        if (responseCode == HttpURLConnection.HTTP_OK) {
            System.out.println("Estado económico del usuario modificado correctamente.");
            JOptionPane.showMessageDialog(null, "Estado económico del usuario modificado correctamente.");
            cargarDatosTabla();  // Recargar la tabla para reflejar los cambios
        } else {
            System.err.println("Error al modificar estado económico del usuario. Código de respuesta: " + responseCode);
            JOptionPane.showMessageDialog(null, "Error al modificar estado económico del usuario.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al modificar estado económico del usuario.");
    }
}


// Método para manejar la modificación de usuario
private void manejarModificacionUsuario() {
    int filaSeleccionada = TableUsuarios.getSelectedRow();

    if (filaSeleccionada != -1) {
        int usuarioId = (int) TableUsuarios.getValueAt(filaSeleccionada, 0);

        int confirmacion = JOptionPane.showConfirmDialog(null,
            "¿Está seguro de que desea modificar los datos de este usuario?",
            "Confirmar modificación",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
                modificarUsuario(usuarioId);
                modificarGeneroUsuarioSeleccionado(usuarioId);
                modificarEstadoEconomicoUsuarioSeleccionado(usuarioId);
                imprimirMapaGeneros();
            
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione un usuario de la tabla.");
    }
}


 
//-----------------------------------------------------FIN MODIFICAR------------------------------------------------------------------------
    
//-----------------------------------------------------INICIO ELIMINAR----------------------------------------------------------------------
    
    // Método para eliminar un usuario a través de la API
    private void eliminarUsuario(int usuarioId) {
        String urlString = "http://127.0.0.1:8000/eliminar_usuario/" + usuarioId + "/"; // URL de la API para eliminar

        try {
            // Crear la URL y la conexión
            URL url = new URL(urlString);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();

            // Configurar el método GET y los encabezados
            connection.setRequestMethod("GET");
            connection.setRequestProperty("Authorization", "Token " + token);  // Token de autenticación
            //connection.setRequestProperty("Authorization", "Token " + token2);
            connection.setRequestProperty("Accept", "application/json");

            // Conectar y obtener la respuesta
            connection.connect();
            int responseCode = connection.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_NO_CONTENT) {
                JOptionPane.showMessageDialog(null, "Usuario eliminado correctamente.");
                // Aquí puedes actualizar la tabla o hacer otras acciones
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar usuario. Código de respuesta: " + responseCode);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al eliminar usuario.");
        }
    }
    

    // Método común para manejar la eliminación del usuario
    private void manejarEliminacionUsuario() {
        // Obtener la fila seleccionada
        int filaSeleccionada = TableUsuarios.getSelectedRow();

        if (filaSeleccionada != -1) {
            // Obtener el ID del usuario en la primera columna (suponiendo que el ID está en la columna 0)
            int usuarioId = (int) TableUsuarios.getValueAt(filaSeleccionada, 0);

            // Mostrar un cuadro de confirmación para eliminar el usuario
            int confirmacion = JOptionPane.showConfirmDialog(null, 
                "¿Está seguro de que desea eliminar este usuario?", 
                "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                eliminarUsuario(usuarioId); // Llamar al método de eliminación
                cargarDatosTabla();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un usuario de la tabla.");
        }
    }

    // Método para agregar el listener al hacer clic en la fila de la tabla
    private void agregarListenerTabla() {
        TableUsuarios.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                manejarEliminacionUsuario(); // Llamar al método común
            }
        });
    }

    
//-----------------------------------------------------FIN ELIMINAR-------------------------------------------------------------------------

    
//-----------------------------------------------------INICIO SELECCIONAR USUARIO-----------------------------------------------------------
   // Método para cargar los datos del usuario seleccionado
private void seleccionarUsuario(int usuarioId) {
    String urlString = "http://127.0.0.1:8000/api/perfilusuario/" + usuarioId + "/"; // URL de la API para obtener datos

    try {
        // Crear la URL y la conexión
        URL url = new URL(urlString);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();

        // Configurar el método GET y los encabezados
        connection.setRequestMethod("GET");
        connection.setRequestProperty("Authorization", "Token " + token);  // Token de autenticación
        connection.setRequestProperty("Accept", "application/json");

        // Conectar y obtener la respuesta
        connection.connect();
        int responseCode = connection.getResponseCode();

        if (responseCode == HttpURLConnection.HTTP_OK) {
            // Leer la respuesta de la API
            BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            StringBuilder response = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                response.append(line);
            }

            // Convertir la respuesta en un JSONObject
            JSONObject jsonResponse = new JSONObject(response.toString());

            // Procesar estado económico como objeto JSON
            String estadoEconomico = "N/A";
            JSONObject estadoEconomicoObj = jsonResponse.optJSONObject("estado_economico");
            if (estadoEconomicoObj != null) {
                estadoEconomico = estadoEconomicoObj.optString("descripcion", "N/A");
            }

            // Procesar genero como objeto JSON o cadena simple
            String genero = "N/A";
            JSONObject generoObj = jsonResponse.optJSONObject("genero");
            if (generoObj != null) {
                genero = generoObj.optString("descripcion", "N/A");
            } else {
                // Si genero es un valor simple, asignarlo directamente
                genero = jsonResponse.optString("genero", "N/A");
            }

            // Obtener los datos de usuario_django (que es un diccionario)
            String firstName = "N/A";
            String lastName = "N/A";
            String username = "N/A";
            String email = "N/A";
            if (jsonResponse.has("usuario_django")) {
                JSONObject usuarioDjango = jsonResponse.getJSONObject("usuario_django");
                firstName = usuarioDjango.optString("first_name", "N/A");
                lastName = usuarioDjango.optString("last_name", "N/A");
                username = usuarioDjango.optString("username", "N/A");
                email = usuarioDjango.optString("email", "N/A");
            }

            // Obtener otros datos del usuario
            String rut = jsonResponse.optString("rut", "N/A");
            String telefono = jsonResponse.optString("telefono", "N/A");

            // Mostrar los datos en los campos correspondientes
            txtNombre.setText(firstName);
            txtApellido.setText(lastName);
            txtRut.setText(rut);
            txtTelefono.setText(telefono);
            txtUsername.setText(username);  // Asumiendo que tienes un campo para mostrar el username
            txtEmail.setText(email);  // Asumiendo que tienes un campo para mostrar el email

            // Asignar el valor del género al ComboBox correspondiente
            for (int i = 0; i < ComboBoxEsGe.getItemCount(); i++) {
                if (ComboBoxEsGe.getItemAt(i).equals(genero)) {
                    ComboBoxEsGe.setSelectedIndex(i);  // Seleccionar el género
                    break;
                }
            }

            // Asignar el valor del estado económico al ComboBox correspondiente
            for (int i = 0; i < ComboBoxEsEc.getItemCount(); i++) {
                if (ComboBoxEsEc.getItemAt(i).equals(estadoEconomico)) {
                    ComboBoxEsEc.setSelectedIndex(i);  // Seleccionar el estado económico
                    break;
                }
            }

            // Deshabilitar los campos que no deben ser modificados
            txtRut.setEditable(false);
            txtRut.setBackground(Color.GRAY);

        } else {
            JOptionPane.showMessageDialog(null, "Error al obtener datos del usuario.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al seleccionar usuario.");
    }
}



// Método para manejar la selección del usuario en la tabla y cargar datos
private void manejarSeleccionUsuario() {
    // Obtener la fila seleccionada
    int filaSeleccionada = TableUsuarios.getSelectedRow();

    if (filaSeleccionada != -1) {
        // Obtener el ID del usuario en la primera columna (suponiendo que el ID está en la columna 0)
        int usuarioId = (int) TableUsuarios.getValueAt(filaSeleccionada, 0);

        // Confirmación de selección
        int confirmacion = JOptionPane.showConfirmDialog(null,
            "¿Está seguro de que desea cargar los datos de este usuario?",
            "Confirmar selección",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            seleccionarUsuario(usuarioId); // Llamar al método para cargar los datos
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione un usuario de la tabla.");
    }
}
        

//-----------------------------------------------------FIN SELECCIONAR USUARIO--------------------------------------------------------------


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }
    

    

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTEliminarUS;
    private javax.swing.JButton BTModificarUS1;
    private javax.swing.JButton BTSeleccionarUS;
    private javax.swing.JButton BTVolver;
    private javax.swing.JComboBox<String> ComboBoxEsEc;
    private javax.swing.JComboBox<String> ComboBoxEsGe;
    private javax.swing.JTable TableUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables


}
